### ISSUE TITLE
Can't load name changes

### ISSUE THREAD

**Issue by jhordanngs** [ddeeddii/eztools#6]
![image](https://github.com/user-attachments/assets/f69ab00b-d32a-4ec8-a1c5-d9ee4b6e97a7)

**Comment by ddeeddii** [comment]
Thanks for the report, should be fixed with 644250b0bdca499db80c7faa4826ad020d568c07.
Import your mod and export it in order to update it.

**Comment by jhordanngs** [comment]
I solved the error with the encyclopedia mod, but if that's not necessary,
I think it would be better. The less dependent mods I have to install the
better.

Em dom., 29 de set. de 2024 7:53 AM, dedi ***@***.***>
escreveu:

**Comment by jhordanngs** [comment]
![image](https://github.com/user-attachments/assets/e85825c4-086c-42f6-8f0f-f274276f3a28)
Now the error is on line 3. I disable the encyclopedia mod.

**Comment by ddeeddii** [comment]
Very strange, could you send the main.lua and data.lua files from your mod? The bug has definitely been fixed but it's possible your browser has cached the website and did not update it yet.

**Comment by jhordanngs** [comment]
Sure, here it is:
[t.zip](https://github.com/user-attachments/files/17179325/t.zip)

**Comment by ddeeddii** [comment]
It's as I said - the mod has not been updated with the newest version probably because your browser is still accessing the cached website version. Pressing `CTRL + F5` on https://isaac.d3d1.xyz/ezitems and re-exporting your mod should hopefully fix the issue.

**Comment by jhordanngs** [comment]
This really worked, thank you very much for the help. I'm creating a mod that translates the entire game while my country is excluded from the officially existing languages ​​within the game. You saved my job.

**Comment by ddeeddii** [comment]
Glad to help, once again thanks for reporting.
